## **Random forest**

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from pandas import DataFrame,Series
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import matplotlib
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split,cross_val_score, cross_val_predict
import seaborn as sns # plotting library
from sklearn import svm
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [ ]:

dataset_rf=pd.read_excel(r"/content/drive/MyDrive/SEMİ NORMALIZED DATA-building (1).xlsx")
#print(dataset_rf)
dataset_rf=np.array(dataset_rf)

dataset_rf=np.array(dataset_rf[:2926,:])
print(dataset_rf)

[[9.0 1.0 89.0 ... 0.1960484364 0.9 0.03278688525]
 [9.0 1.0 89.0 ... 0.197642588 0.8875 0.04918032787]
 [9.0 1.0 89.0 ... 0.1970145889 0.8875 0.04918032787]
 ...
 [12.0 31.0 89.0 ... 0.0922192522 0.4625 0.6557377049]
 [12.0 31.0 89.0 ... 0.09841873048 0.475 0.6885245902]
 [12.0 31.0 89.0 ... 0.09890180671 0.475 0.737704918]]


In [ ]:
dataset_rf[:2926, 0:4]
dataset_rf[:2926, 11:18]
seminorma_dataset=np.hstack((dataset_rf[:2926, 0:4], dataset_rf[:2926, 11:18]))
print(seminorma_dataset)




x1, y1 = seminorma_dataset[:, 0:8], seminorma_dataset[:, 8:9]

x=np.asarray(x1).astype(np.float32)
y=np.asarray(y1).astype(np.float32)



[[9.0 1.0 89.0 ... 0.1960484364 0.9 0.03278688525]
 [9.0 1.0 89.0 ... 0.197642588 0.8875 0.04918032787]
 [9.0 1.0 89.0 ... 0.1970145889 0.8875 0.04918032787]
 ...
 [12.0 31.0 89.0 ... 0.0922192522 0.4625 0.6557377049]
 [12.0 31.0 89.0 ... 0.09841873048 0.475 0.6885245902]
 [12.0 31.0 89.0 ... 0.09890180671 0.475 0.737704918]]


In [ ]:
y

array([[0.19604844],
       [0.1976426 ],
       [0.19701459],
       ...,
       [0.09221926],
       [0.09841873],
       [0.09890181]], dtype=float32)

In [ ]:
# Splitting the data for training and testing
# split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

rf_regressor = RandomForestRegressor(n_estimators = 500 ,  random_state = 1)
rf_regressor.fit(x_train,y_train)

#Prediction using test set
y_pred = rf_regressor.predict(x_test)


error = mean_absolute_error(y_test, y_pred)
mse=metrics.mean_squared_error(y_test, y_pred)

print(error)

print('mse: %.3f' % error)


<ipython-input-25-1857fd6c35dd>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_regressor.fit(x_train,y_train)


0.07726457118347992
mse: 0.077


In [ ]:
mse_wbe3=metrics.mean_squared_error(y_test[:,0], y_pred[:586,0])

print('Test MSE: ', mse_wbe3)

Test MSE:  0.013545605608496537


In [ ]:
mse_wbcw3=metrics.mean_squared_error(y_test[:,1], y_pred[:586,1])

print('Test MSE: ', mse_wbcw3)

In [ ]:
mse_wbhw3=metrics.mean_squared_error(y_test[:,2], y_pred[:586,2])

print('Test MSE: ', mse_wbhw3)

IndexError: ignored

## **Random forest Input 7 10 Çıkartma According to Correlation Matrix**

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from pandas import DataFrame,Series
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import matplotlib
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split,cross_val_score, cross_val_predict
import seaborn as sns # plotting library
from sklearn import svm
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset_rf=pd.read_excel(r"/content/drive/MyDrive/SE üretim consulting A.Ş/SEMİ NORMALIZED DATA-building (1).xlsx")
dataset_rf=np.array(dataset_rf)

dataset_rf=np.array(dataset_rf[:2926,:])
print(dataset_rf)

[[9.0 1.0 89.0 ... 0.1960484364 0.9 0.03278688525]
 [9.0 1.0 89.0 ... 0.197642588 0.8875 0.04918032787]
 [9.0 1.0 89.0 ... 0.1970145889 0.8875 0.04918032787]
 ...
 [12.0 31.0 89.0 ... 0.0922192522 0.4625 0.6557377049]
 [12.0 31.0 89.0 ... 0.09841873048 0.475 0.6885245902]
 [12.0 31.0 89.0 ... 0.09890180671 0.475 0.737704918]]


In [ ]:
dataset_rf[:2926, 0:4]
dataset_rf[:2926, 11:18]
seminorma_dataset=np.hstack((dataset_rf[:2926, 0:4], dataset_rf[:2926, 11:18]))

In [ ]:
df = pd.DataFrame(seminorma_dataset)
df=df.drop([7, 10], axis = 1)
df=np.array(df)
df

array([[9.0, 1.0, 89.0, ..., 0.0006824607585, 0.1960484364, 0.9],
       [9.0, 1.0, 89.0, ..., 0.0006824607585, 0.197642588, 0.8875],
       [9.0, 1.0, 89.0, ..., 0.0006824607585, 0.1970145889, 0.8875],
       ...,
       [12.0, 31.0, 89.0, ..., 0.00263234864, 0.0922192522, 0.4625],
       [12.0, 31.0, 89.0, ..., 0.00263234864, 0.09841873048, 0.475],
       [12.0, 31.0, 89.0, ..., 0.00263234864, 0.09890180671, 0.475]],
      dtype=object)

In [ ]:
x1, y1 = df[:, 0:3], df[:, 3:9] #

x=np.asarray(x1).astype(np.float32)
y=np.asarray(y1).astype(np.float32)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

rf_regressor = RandomForestRegressor(n_estimators = 500 ,  random_state = 1)
rf_regressor.fit(x_train,y_train)

#Prediction using test set
y_pred = rf_regressor.predict(x_test)


error = mean_absolute_error(y_test, y_pred)
mse=metrics.mean_squared_error(y_test, y_pred)

print(error)

print('mse: %.3f' % error)


101.82990623628955
mse: 101.830


In [ ]:
mse_wbe3=metrics.mean_squared_error(y_test[:,0], y_pred[:586,0])

print('Test MSE: ', mse_wbe3)

Test MSE:  508018.88783592446


In [ ]:
mse_wbcw3=metrics.mean_squared_error(y_test[:,1], y_pred[:586,1])

print('Test MSE: ', mse_wbcw3)

Test MSE:  0.004797324161828948


In [ ]:
mse_wbhw3=metrics.mean_squared_error(y_test[:,2], y_pred[:586,2])

print('Test MSE: ', mse_wbhw3)

Test MSE:  0.010330532495960361


## **Random forest Input 1 2 3 5 Çıkarıldı According to Correlation Matrix**

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from pandas import DataFrame,Series
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import matplotlib
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split,cross_val_score, cross_val_predict
import seaborn as sns # plotting library
from sklearn import svm
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset_rf=pd.read_excel(r"/content/drive/MyDrive/SE üretim consulting A.Ş/SEMİ NORMALIZED DATA-building (1).xlsx")
dataset_rf=np.array(dataset_rf)

dataset_rf=np.array(dataset_rf[:2926,:])
print(dataset_rf)

[[9.0 1.0 89.0 ... 0.1960484364 0.9 0.03278688525]
 [9.0 1.0 89.0 ... 0.197642588 0.8875 0.04918032787]
 [9.0 1.0 89.0 ... 0.1970145889 0.8875 0.04918032787]
 ...
 [12.0 31.0 89.0 ... 0.0922192522 0.4625 0.6557377049]
 [12.0 31.0 89.0 ... 0.09841873048 0.475 0.6885245902]
 [12.0 31.0 89.0 ... 0.09890180671 0.475 0.737704918]]


In [ ]:
dataset_rf[:2926, 0:4]
dataset_rf[:2926, 11:18]
seminorma_dataset=np.hstack((dataset_rf[:2926, 0:4], dataset_rf[:2926, 11:18]))

In [ ]:
df = pd.DataFrame(seminorma_dataset)
df=df.drop([0, 1, 2, 5], axis = 1)
df=np.array(df)
df

array([[200, 0.818369453, 0.0006824607585, ..., 0.1960484364, 0.9,
        0.03278688525],
       [300, 0.8059855521, 0.0006824607585, ..., 0.197642588, 0.8875,
        0.04918032787],
       [400, 0.7956656347, 0.0006824607585, ..., 0.1970145889, 0.8875,
        0.04918032787],
       ...,
       [2100, 0.4489164087, 0.00263234864, ..., 0.0922192522, 0.4625,
        0.6557377049],
       [2200, 0.4509803922, 0.00263234864, ..., 0.09841873048, 0.475,
        0.6885245902],
       [2300, 0.439628483, 0.00263234864, ..., 0.09890180671, 0.475,
        0.737704918]], dtype=object)

In [ ]:
x1, y1 = df[:, 0:3], df[:, 3:7] #

x=np.asarray(x1).astype(np.float32)
y=np.asarray(y1).astype(np.float32)



In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

rf_regressor = RandomForestRegressor(n_estimators = 500 ,  random_state = 1)
rf_regressor.fit(x_train,y_train)

#Prediction using test set
y_pred = rf_regressor.predict(x_test)


error = mean_absolute_error(y_test, y_pred)
mse=metrics.mean_squared_error(y_test, y_pred)

print(error)

print('mse: %.3f' % error)


0.09491025253844923
mse: 0.095


In [ ]:
mse_wbe3=metrics.mean_squared_error(y_test[:,0], y_pred[:586,0])

print('Test MSE: ', mse_wbe3)

Test MSE:  0.028831845576125396


In [ ]:
mse_wbcw3=metrics.mean_squared_error(y_test[:,1], y_pred[:586,1])

print('Test MSE: ', mse_wbcw3)

Test MSE:  0.042902557062622616


In [ ]:
mse_wbhw3=metrics.mean_squared_error(y_test[:,2], y_pred[:586,2])

print('Test MSE: ', mse_wbhw3)

Test MSE:  0.00354601258993226


## **Random forest 1 Output Azaltma**

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from pandas import DataFrame,Series
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import matplotlib
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split,cross_val_score, cross_val_predict
import seaborn as sns # plotting library
from sklearn import svm
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [ ]:

dataset_rf=pd.read_excel(r"/content/drive/MyDrive/SE üretim consulting A.Ş/SEMİ NORMALIZED DATA-building (1).xlsx")
#print(dataset_rf)
dataset_rf=np.array(dataset_rf)

dataset_rf=np.array(dataset_rf[:2926,:])
print(dataset_rf)

[[9.0 1.0 89.0 ... 0.1960484364 0.9 0.03278688525]
 [9.0 1.0 89.0 ... 0.197642588 0.8875 0.04918032787]
 [9.0 1.0 89.0 ... 0.1970145889 0.8875 0.04918032787]
 ...
 [12.0 31.0 89.0 ... 0.0922192522 0.4625 0.6557377049]
 [12.0 31.0 89.0 ... 0.09841873048 0.475 0.6885245902]
 [12.0 31.0 89.0 ... 0.09890180671 0.475 0.737704918]]


In [ ]:
df = pd.DataFrame(seminorma_dataset)
df

0     1     2     3         4         5         6         7   \
0      9.0   1.0  89.0   200  0.818369  0.828829  0.000682  0.392784   
1      9.0   1.0  89.0   300  0.805986  0.842342  0.000682  0.409278   
2      9.0   1.0  89.0   400  0.795666  0.873874  0.000682  0.397938   
3      9.0   1.0  89.0   500  0.788442  0.887387   0.00078  0.313402   
4      9.0   1.0  89.0   600   0.78741  0.896396   0.00078  0.292784   
...    ...   ...   ...   ...       ...       ...       ...       ...   
2921  12.0  31.0  89.0  1900  0.464396  0.112613   0.00234   0.18866   
2922  12.0  31.0  89.0  2000  0.453044  0.117117  0.002437   0.12268   
2923  12.0  31.0  89.0  2100  0.448916  0.121622  0.002632  0.108763   
2924  12.0  31.0  89.0  2200   0.45098  0.126126  0.002632  0.120619   
2925  12.0  31.0  89.0  2300  0.439628  0.126126  0.002632  0.165979   

            8       9         10  
0     0.196048     0.9  0.032787  
1     0.197643  0.8875   0.04918  
2     0.197015  0.8875   0.04918  
3     0.193585  0.8875  0.065574  
4     0.199301   0.875  0.065574  
...        ...     ...       ...  
2921  0.098982   0.475  0.688525  
2922  0.091495   0.475  0.754098  
2923  0.092219  0.4625  0.655738  
2924  0.098419   0.475  0.688525  
2925  0.098902   0.475  0.737705  

[2926 rows x 11 columns]

In [ ]:
dataset_rf[:2926, 0:4]
dataset_rf[:2926, 11:18]
seminorma_dataset=np.hstack((dataset_rf[:2926, 0:4], dataset_rf[:2926, 11:18]))

df = pd.DataFrame(seminorma_dataset)
df=df.drop([10], axis = 1)
df=np.array(df)

#scaler = MinMaxScaler()

#df = scaler.fit_transform(data)  #conti. formata getiriyor
#dataset = seminorma_dataset

x1, y1 = seminorma_dataset[:, 0:8], seminorma_dataset[:, 8:10] #

x=np.asarray(x1).astype(np.float32)
y=np.asarray(y1).astype(np.float32)



In [ ]:
df

array([[9.0, 1.0, 89.0, ..., 0.3927835052, 0.1960484364, 0.9],
       [9.0, 1.0, 89.0, ..., 0.4092783505, 0.197642588, 0.8875],
       [9.0, 1.0, 89.0, ..., 0.3979381443, 0.1970145889, 0.8875],
       ...,
       [12.0, 31.0, 89.0, ..., 0.1087628866, 0.0922192522, 0.4625],
       [12.0, 31.0, 89.0, ..., 0.1206185567, 0.09841873048, 0.475],
       [12.0, 31.0, 89.0, ..., 0.1659793814, 0.09890180671, 0.475]],
      dtype=object)

In [ ]:
y

array([[0.19604844],
       [0.1976426 ],
       [0.19701459],
       ...,
       [0.09221926],
       [0.09841873],
       [0.09890181]], dtype=float32)

In [ ]:
# Splitting the data for training and testing
# split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

rf_regressor = RandomForestRegressor(n_estimators = 500 ,  random_state = 1)
rf_regressor.fit(x_train,y_train)

#Prediction using test set
y_pred = rf_regressor.predict(x_test)


error = mean_absolute_error(y_test, y_pred)
mse=metrics.mean_squared_error(y_test, y_pred)

print(error)

print('mse: %.3f' % error)


0.05105952515298084
mse: 0.051


In [ ]:
mse_wbe3=metrics.mean_squared_error(y_test[:,0], y_pred[:586,0])

print('Test MSE: ', mse_wbe3)

Test MSE:  0.014050795904007264


In [ ]:
mse_wbcw3=metrics.mean_squared_error(y_test[:,1], y_pred[:586,1])

print('Test MSE: ', mse_wbcw3)

Test MSE:  0.0012782953277846382


## **Random forest 2 Output Azaltma**

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from pandas import DataFrame,Series
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import matplotlib
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split,cross_val_score, cross_val_predict
import seaborn as sns # plotting library
from sklearn import svm
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [ ]:

dataset_rf=pd.read_excel(r"/content/drive/MyDrive/SE üretim consulting A.Ş/SEMİ NORMALIZED DATA-building (1).xlsx")
#print(dataset_rf)
dataset_rf=np.array(dataset_rf)

dataset_rf=np.array(dataset_rf[:2926,:])
print(dataset_rf)

[[9.0 1.0 89.0 ... 0.1960484364 0.9 0.03278688525]
 [9.0 1.0 89.0 ... 0.197642588 0.8875 0.04918032787]
 [9.0 1.0 89.0 ... 0.1970145889 0.8875 0.04918032787]
 ...
 [12.0 31.0 89.0 ... 0.0922192522 0.4625 0.6557377049]
 [12.0 31.0 89.0 ... 0.09841873048 0.475 0.6885245902]
 [12.0 31.0 89.0 ... 0.09890180671 0.475 0.737704918]]


In [ ]:
df = pd.DataFrame(seminorma_dataset)
df

0     1     2     3         4         5         6         7   \
0      9.0   1.0  89.0   200  0.818369  0.828829  0.000682  0.392784   
1      9.0   1.0  89.0   300  0.805986  0.842342  0.000682  0.409278   
2      9.0   1.0  89.0   400  0.795666  0.873874  0.000682  0.397938   
3      9.0   1.0  89.0   500  0.788442  0.887387   0.00078  0.313402   
4      9.0   1.0  89.0   600   0.78741  0.896396   0.00078  0.292784   
...    ...   ...   ...   ...       ...       ...       ...       ...   
2921  12.0  31.0  89.0  1900  0.464396  0.112613   0.00234   0.18866   
2922  12.0  31.0  89.0  2000  0.453044  0.117117  0.002437   0.12268   
2923  12.0  31.0  89.0  2100  0.448916  0.121622  0.002632  0.108763   
2924  12.0  31.0  89.0  2200   0.45098  0.126126  0.002632  0.120619   
2925  12.0  31.0  89.0  2300  0.439628  0.126126  0.002632  0.165979   

            8       9         10  
0     0.196048     0.9  0.032787  
1     0.197643  0.8875   0.04918  
2     0.197015  0.8875   0.04918  
3     0.193585  0.8875  0.065574  
4     0.199301   0.875  0.065574  
...        ...     ...       ...  
2921  0.098982   0.475  0.688525  
2922  0.091495   0.475  0.754098  
2923  0.092219  0.4625  0.655738  
2924  0.098419   0.475  0.688525  
2925  0.098902   0.475  0.737705  

[2926 rows x 11 columns]

In [ ]:
dataset_rf[:2926, 0:4]
dataset_rf[:2926, 11:18]
seminorma_dataset=np.hstack((dataset_rf[:2926, 0:4], dataset_rf[:2926, 11:18]))

df = pd.DataFrame(seminorma_dataset)
df=df.drop([9, 10], axis = 1)
df=np.array(df)

#scaler = MinMaxScaler()

#df = scaler.fit_transform(data)  #conti. formata getiriyor
#dataset = seminorma_dataset

x1, y1 = seminorma_dataset[:, 0:8], seminorma_dataset[:, 8:9]

x=np.asarray(x1).astype(np.float32)
y=np.asarray(y1).astype(np.float32)



In [ ]:
df

array([[9.0, 1.0, 89.0, ..., 0.0006824607585, 0.3927835052, 0.1960484364],
       [9.0, 1.0, 89.0, ..., 0.0006824607585, 0.4092783505, 0.197642588],
       [9.0, 1.0, 89.0, ..., 0.0006824607585, 0.3979381443, 0.1970145889],
       ...,
       [12.0, 31.0, 89.0, ..., 0.00263234864, 0.1087628866, 0.0922192522],
       [12.0, 31.0, 89.0, ..., 0.00263234864, 0.1206185567,
        0.09841873048],
       [12.0, 31.0, 89.0, ..., 0.00263234864, 0.1659793814,
        0.09890180671]], dtype=object)

In [ ]:
y

array([[0.19604844],
       [0.1976426 ],
       [0.19701459],
       ...,
       [0.09221926],
       [0.09841873],
       [0.09890181]], dtype=float32)

In [ ]:
# Splitting the data for training and testing
# split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

rf_regressor = RandomForestRegressor(n_estimators = 500 ,  random_state = 1)
rf_regressor.fit(x_train,y_train)

#Prediction using test set
y_pred = rf_regressor.predict(x_test)


error = mean_absolute_error(y_test, y_pred)
mse=metrics.mean_squared_error(y_test, y_pred)

print(error)

print('mse: %.3f' % error)


<ipython-input-57-1857fd6c35dd>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_regressor.fit(x_train,y_train)


0.07726457118347992
mse: 0.077


In [ ]:
#mse_wbe3=metrics.mean_squared_error(y_test[:,0], y_pred[:586,0])
mse_wbe3=metrics.mean_squared_error(y_test, y_pred)
print('Test MSE: ', mse_wbe3)

Test MSE:  0.013545605608496537


## **Decision tree**

In [ ]:
#WORKING - DATA

import numpy as np # linear algebra
import pandas as pd # data processing
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from pandas import DataFrame,Series
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import matplotlib
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split,cross_val_score, cross_val_predict
import seaborn as sns # plotting library
from sklearn import svm




In [ ]:

data=pd.read_excel(r"/content/drive/MyDrive/DATA-building.xlsx")
print(data)


      MONTH  DAY  YEAR  HOUR  TEMP   HUMID  SOLAR  WIND     WBE  WBCW  WBHW
0         9    1    89   200  81.9  0.0184    0.0  7.62  496.07   7.2   0.4
1         9    1    89   300  80.7  0.0187    0.0  7.94  497.06   7.1   0.5
2         9    1    89   400  79.7  0.0194    0.0  7.72  496.67   7.1   0.5
3         9    1    89   500  79.0  0.0197    0.1  6.08  494.54   7.1   0.6
4         9    1    89   600  78.9  0.0199    0.1  5.68  498.09   7.0   0.6
...     ...  ...   ...   ...   ...     ...    ...   ...     ...   ...   ...
2921     12   31    89  1900  47.6  0.0025    1.7  3.66  435.79   3.8   4.4
2922     12   31    89  2000  46.5  0.0026    1.8  2.38  431.14   3.8   4.8
2923     12   31    89  2100  46.1  0.0027    2.0  2.11  431.59   3.7   4.2
2924     12   31    89  2200  46.3  0.0028    2.0  2.34  435.44   3.8   4.4
2925     12   31    89  2300  45.2  0.0028    2.0  3.22  435.74   3.8   4.7

[2926 rows x 11 columns]


In [ ]:

scaler = MinMaxScaler()

df = scaler.fit_transform(data)  #conti. formata getiriyor

dataset = df
# split into input (X) and output (Y) variables
# split into input and output columns
x1, y1 = dataset[:, 0:8], dataset[:, 8:11]

x=np.asarray(x1).astype(np.float32)
y=np.asarray(y1).astype(np.float32)

# Splitting the data for training and testing
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3, random_state=1,shuffle=True)   #30% test data, 70% training data

print(x_test.shape)
print(y_test.shape)


#print(x_train)
#print(y_train)

(878, 8)
(878, 3)


In [ ]:


dt_regressor = DecisionTreeRegressor(random_state = 1)
dt_regressor.fit(x_train,y_train)
#Predicting using test set
y_pred_test = dt_regressor.predict(x_test)

y_pred_train = dt_regressor.predict(x_train)

In [ ]:
mae=metrics.mean_absolute_error(y_test, y_pred_test)
mse=metrics.mean_squared_error(y_test, y_pred_test)
r2=metrics.r2_score(y_test, y_pred_test)

#print(y_pred-y_test)

# Printing the metrics
print('Test R2 square:',r2)
print('Test MAE: ', mae)
print('Test MSE: ', mse)

#Prediction using training set
y_pred = dt_regressor.predict(x_train)
mae=metrics.mean_absolute_error(y_train, y_pred_train)
mse=metrics.mean_squared_error(y_train, y_pred_train)
r2=metrics.r2_score(y_train, y_pred_train)




# Printing the metrics
print('Train R2 square:',r2)
print('Train MAE: ', mae)
print('Train MSE: ', mse)

Test R2 square: 0.8251467445868087
Test MAE:  0.04832573296804895
Test MSE:  0.009142265898911248
Train R2 square: 1.0
Train MAE:  0.0
Train MSE:  0.0


In [ ]:
mae=metrics.mean_absolute_error(y_test[:,0], y_pred_test[:,0])
mse_wbe=metrics.mean_squared_error(y_test[:,0], y_pred_test[:,0])
r2=metrics.r2_score(y_test[:,0], y_pred_test[:,0])
# Printing the metrics
print('Test R2 square:',r2)
print('Test MAE: ', mae)
print('Test MSE: ', mse_wbe)

Test R2 square: 0.6725832510713701
Test MAE:  0.07274335698735877
Test MSE:  0.020582846477430777


In [ ]:
mae=metrics.mean_absolute_error(y_test[:,1], y_pred_test[:,1])
mse_wbcw=metrics.mean_squared_error(y_test[:,1],y_pred_test[:,1])
r2=metrics.r2_score(y_test[:,1], y_pred_test[:,1])
# Printing the metrics
print('Test R2 square:',r2)
print('Test MAE: ', mae)
print('Test MSE: ', mse_wbcw)

Test R2 square: 0.8832824383169169
Test MAE:  0.031548976222507165
Test MSE:  0.0027598236336860856


In [ ]:
mae=metrics.mean_absolute_error(y_test[:,2], y_pred_test[:,2])
mse_wbhw=metrics.mean_squared_error(y_test[:,2], y_pred_test[:,2])
r2=metrics.r2_score(y_test[:,2], y_pred_test[:,2])
# Printing the metrics
print('Test R2 square:',r2)
print('Test MAE: ', mae)
print('Test MSE: ', mse_wbhw)

Test R2 square: 0.919574542078749
Test MAE:  0.04068486569428091
Test MSE:  0.004084127585617042


## **Decision tree**

In [ ]:
#WORKING - DATA

import numpy as np # linear algebra
import pandas as pd # data processing
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from pandas import DataFrame,Series
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import matplotlib
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split,cross_val_score, cross_val_predict
import seaborn as sns # plotting library
from sklearn import svm




In [ ]:

dataset_rf=pd.read_excel(r"/content/drive/MyDrive/SEMİ NORMALIZED DATA-building (1).xlsx")
#print(dataset_rf)
dataset_rf=np.array(dataset_rf)

dataset_rf=np.array(dataset_rf[:2926,:])
print(dataset_rf)

[[9.0 1.0 89.0 ... 0.1960484364 0.9 0.03278688525]
 [9.0 1.0 89.0 ... 0.197642588 0.8875 0.04918032787]
 [9.0 1.0 89.0 ... 0.1970145889 0.8875 0.04918032787]
 ...
 [12.0 31.0 89.0 ... 0.0922192522 0.4625 0.6557377049]
 [12.0 31.0 89.0 ... 0.09841873048 0.475 0.6885245902]
 [12.0 31.0 89.0 ... 0.09890180671 0.475 0.737704918]]


In [ ]:
dataset_rf[:2926, 0:4]
dataset_rf[:2926, 11:18]
seminorma_dataset=np.hstack((dataset_rf[:2926, 0:4], dataset_rf[:2926, 11:18]))
#print(seminorma_dataset)



In [ ]:
df = pd.DataFrame(seminorma_dataset)
df.drop([0, 1, 2, 5], axis = 1)
df=np.array(df)


In [ ]:



#scaler = MinMaxScaler()

#df = scaler.fit_transform(data)  #conti. formata getiriyor
#dataset = seminorma_dataset

x1, y1 = df[:, 0:3], seminorma_dataset[:, 3:7] #

x=np.asarray(x1).astype(np.float32)
y=np.asarray(y1).astype(np.float32)



x=np.asarray(x1).astype(np.float32)
y=np.asarray(y1).astype(np.float32)

# Splitting the data for training and testing
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3, random_state=1,shuffle=True)   #30% test data, 70% training data

print(x_test.shape)
print(y_test.shape)


#print(x_train)
#print(y_train)

(878, 3)
(878, 4)


In [ ]:


dt_regressor = DecisionTreeRegressor(random_state = 1)
dt_regressor.fit(x_train,y_train)
#Predicting using test set
y_pred_test = dt_regressor.predict(x_test)

y_pred_train = dt_regressor.predict(x_train)

In [ ]:
mae=metrics.mean_absolute_error(y_test, y_pred_test)
mse=metrics.mean_squared_error(y_test, y_pred_test)
r2=metrics.r2_score(y_test, y_pred_test)

#print(y_pred-y_test)

# Printing the metrics
print('Test R2 square:',r2)
print('Test MAE: ', mae)
print('Test MSE: ', mse)

#Prediction using training set
y_pred = dt_regressor.predict(x_train)
mae=metrics.mean_absolute_error(y_train, y_pred_train)
mse=metrics.mean_squared_error(y_train, y_pred_train)
r2=metrics.r2_score(y_train, y_pred_train)




# Printing the metrics
print('Train R2 square:',r2)
print('Train MAE: ', mae)
print('Train MSE: ', mse)

Test R2 square: 0.39962559917413304
Test MAE:  153.6622150460999
Test MSE:  127973.21310399083
Train R2 square: 0.4468084836057112
Train MAE:  149.50595859483755
Train MSE:  118946.14669042961


In [ ]:
mae=metrics.mean_absolute_error(y_test[:,0], y_pred_test[:,0])
mse_wbe=metrics.mean_squared_error(y_test[:,0], y_pred_test[:,0])
r2=metrics.r2_score(y_test[:,0], y_pred_test[:,0])
# Printing the metrics
print('Test R2 square:',r2)
print('Test MAE: ', mae)
print('Test MSE: ', mse_wbe)

Test R2 square: -0.09716641240570145
Test MAE:  614.3253332778588
Test MSE:  511892.77733930276


In [ ]:
mae=metrics.mean_absolute_error(y_test[:,1], y_pred_test[:,1])
mse_wbcw=metrics.mean_squared_error(y_test[:,1],y_pred_test[:,1])
r2=metrics.r2_score(y_test[:,1], y_pred_test[:,1])
# Printing the metrics
print('Test R2 square:',r2)
print('Test MAE: ', mae)
print('Test MSE: ', mse_wbcw)

Test R2 square: 0.8592961252102359
Test MAE:  0.0580929396986581
Test MSE:  0.004894729651186428


In [ ]:
mae=metrics.mean_absolute_error(y_test[:,2], y_pred_test[:,2])
mse_wbhw=metrics.mean_squared_error(y_test[:,2], y_pred_test[:,2])
r2=metrics.r2_score(y_test[:,2], y_pred_test[:,2])
# Printing the metrics
print('Test R2 square:',r2)
print('Test MAE: ', mae)
print('Test MSE: ', mse_wbhw)

Test R2 square: 0.8078861091524024
Test MAE:  0.07454585988925048
Test MSE:  0.010747579128412909
